name: CI

on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ['3.9', '3.13']
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install poetry
        run: make poetry-download

      - name: Set up cache
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ matrix.python-version }}-${{ hashFiles('pyproject.toml') }}-${{ hashFiles('poetry.lock') }}

      - name: Install dependencies (patched)
        run: |
          poetry config virtualenvs.in-project true
          poetry install --no-root || {
            echo "❌ Poetry install failed — attempting downgrade fix"
            poetry remove safety
            poetry add safety@3.2.13
            poetry install --no-root
          }

      - name: Run tests
        run: |
          make test

      - name: Archive Coverage Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html-report-${{ matrix.python-version }}
          path: htmlcov
          retention-days: 5
