name: Lint

on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ['3.10']

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install poetry
        run: make poetry-download

      - name: Set up cache
        uses: actions/cache@v4
        with:
          path: |
            .venv
            ~/.cache/pre-commit
          key: venv-${{ matrix.python-version }}-${{ hashFiles('poetry.lock') }}-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Install dependencies
        run: |
          poetry config virtualenvs.in-project true
          make install

      # ✅ Guard step to enforce attribution file
      - name: Ensure KIN_CLAIM.txt attribution
        run: |
          CLAIM="KinLend Attribution Verified by Keeper - Vault f303 Origin"
          if ! grep -Fxq "$CLAIM" KIN_CLAIM.txt 2>/dev/null; then
            echo "$CLAIM" > KIN_CLAIM.txt
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add KIN_CLAIM.txt
            git commit -m "Ensure attribution line in KIN_CLAIM.txt"
            git push
          fi

      - name: Lint
        run: |
          make pre-commit
