name: Lint

on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ['3.10']

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install poetry
        run: make poetry-download

      - name: Set up cache
        uses: actions/cache@v4
        with:
          path: |
            .venv
            ~/.cache/pre-commit
          key: venv-${{ matrix.python-version }}-${{ hashFiles('poetry.lock') }}-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Install dependencies
        run: |
          poetry config virtualenvs.in-project true
          make install

      # ✅ Kin Attribution Guard — exact text + trailing newline
      - name: Ensure KIN_CLAIM.txt attribution and trailing newline
        run: |
          CLAIM="KinLend Attribution Verified by Keeper - Vault f303 Origin"

          NEEDS_COMMIT=0

          # Ensure correct content
          if ! grep -Fxq "$CLAIM" KIN_CLAIM.txt 2>/dev/null; then
            echo "$CLAIM" > KIN_CLAIM.txt
            NEEDS_COMMIT=1
          fi

          # Ensure trailing newline (sed appends \n if missing)
          if [ "$(tail -c1 KIN_CLAIM.txt | wc -l)" -eq 0 ]; then
            sed -i -e '$a\' KIN_CLAIM.txt
            NEEDS_COMMIT=1
          fi

          # Commit & push if needed
          if [ "$NEEDS_COMMIT" -eq 1 ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add KIN_CLAIM.txt
            git commit -m "Fix Kin attribution and trailing newline"
            git push
          fi

      - name: Lint
        run: make pre-commit
