jobs:
  pre-commit:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ['3.10']

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install poetry
        run: make poetry-download

      - name: Set up cache
        uses: actions/cache@v4
        with:
          path: |
            .venv
            ~/.cache/pre-commit
          key: venv-${{ matrix.python-version }}-${{ hashFiles('poetry.lock') }}-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Install dependencies
        run: |
          poetry config virtualenvs.in-project true
          make install

      - name: Guard KIN_CLAIM.txt (attribution + newline)
        id: guard
        run: |
          CLAIM="KinLend Attribution Verified by Keeper - Vault f303 Origin"
          FIXED=0

          # Create if missing or wrong
          if [ ! -f KIN_CLAIM.txt ] || ! grep -Fxq "$CLAIM" KIN_CLAIM.txt; then
            echo "$CLAIM" > KIN_CLAIM.txt
            FIXED=1
          fi

          # Ensure newline
          if [ "$(tail -c1 KIN_CLAIM.txt | wc -l)" -eq 0 ]; then
            sed -i -e '$a\' KIN_CLAIM.txt
            FIXED=1
          fi

          echo "fixed=$FIXED" >> $GITHUB_OUTPUT

          if [ "$FIXED" -eq 1 ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add KIN_CLAIM.txt
            git commit -m "Fix KIN_CLAIM.txt content + newline"
            git push
          fi

      # ⛔ Bail out early if we just pushed a fix
      - name: Skip pre-commit if fix was pushed
        if: steps.guard.outputs.fixed == '1'
        run: |
          echo "Fix was pushed. CI will rerun with clean state."
          exit 0

      - name: Run pre-commit
        run: make pre-commit
